version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: telecom_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_secure_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - FLASK_ENV=production
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html
      - /home/ubuntu/telecom-inventory/nginx.conf:/etc/nginx/conf.d/nginx.conf  # Absolute path fix
    ports:
      - "8880:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
